<?php

namespace Database\Seeders;

use App\Models\Part;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PartSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $itemArr = [
            [
                'description' => 'TUBE, PERF, 7.690"OD, 200"OAL',
                'customer_id' => 1,
                'type' => '316L',
                'part' => '01847572',
                'gage' => 12,
                'holes' => 0.06,
                'centers' => 0.06,
                'pattern' => 'Inline',
                'dim' => 7.69,
                'dim_plus' => 0.03,
                'dim_minus' => 0.03,
                'is_od' => 1,
                'cutoff_length' => 202,
                'finished_length' => 200,
                'final_length_geo' => 0,
                'length_plus' => 0.125,
                'length_minus' => 0.125,
                'strip' => 7,
                'drift' => '7.460',
                'mill' => 1,
                'ring1_min_input' => 0,
                'ring1_max_input' => 0,
                'ring2_min_input' => 0,
                'ring2_max_input' => 0,
                'die' => 180,
                'filter_mesh' => '',
                'notes' => 'Dimple depth is 0.060". 2.19" rings, +0.250"/-0.130". Ring ID to be ground flush. Use 5.985" to drift. Ends must be cleaned.',
                'drawing' => '',
                'insp_notes' => 'Dimple depth is 0.060". 2.19" rings, +0.250"/-0.130". Ring ID to be ground flush. Use 5.985" to drift. Ends must be cleaned.',
                'layer_1_mesh' => '',
                'layer_1_width' => 0,
                'layer_2_mesh' => '',
                'layer_2_width' => 0,
                'drainage_1_mesh' => '',
                'drainage_1_width' => '0',
                'drainage_2_mesh' => '',
                'drainage_2_width' => 0,
                'blank_length_plus' => 0,
                'blank_length_minus' => 0,
                'depth_of_dimple' => 0,
                'is_louver' => 0,
                'depth_of_dimple_plus' => 0,
                'depth_of_dimple_minus' => 0,
                'blank_end' => 0,
                'blank_end_plus' => 0,
                'blank_end_minus' => 0,
                'cutoff_length_plus' => 0,
                'cutoff_length_minus' => 0,
                'drawing_number' => '',
                'table_height' => 0,
                'die_position' => 0,
                'shrouded_cutoff_length' => 0,
                'shrouded_cutoff_length_plus' => 0,
                'shrouded_cutoff_length_minus' => 0,
                'rouselle' => 0,
                'niagara' => 0,
                'seyi' => 0,
                'blank_area_input' => 0,
                'cycles_input' => 0,
                'linear_feet_input' => 0,
                'die_stamp' => '1/2 x 1 inline',
                'progression' => 0,
                'geo_job' => 0,
                'act_mill_angle' => 0,
                'table_position' => 0
            ],
            [
                'description' => '7.00 IN SHRD, 304L, 14GA',
                'customer_id' => 2,
                'type' => '320L',
                'part' => '01847573',
                'gage' => 15,
                'holes' => 0.06,
                'centers' => 0.06,
                'pattern' => 'Inline',
                'dim' => 7.69,
                'dim_plus' => 0.03,
                'dim_minus' => 0.03,
                'is_od' => 1,
                'cutoff_length' => 202,
                'finished_length' => 200,
                'final_length_geo' => 0,
                'length_plus' => 0.125,
                'length_minus' => 0.125,
                'strip' => 7,
                'drift' => '7.460',
                'mill' => 1,
                'ring1_min_input' => 0,
                'ring1_max_input' => 0,
                'ring2_min_input' => 0,
                'ring2_max_input' => 0,
                'die' => 180,
                'filter_mesh' => '',
                'notes' => 'Dimple depth is 0.060". 2.19" rings, +0.250"/-0.130". Ring ID to be ground flush. Use 5.985" to drift. Ends must be cleaned.',
                'drawing' => '',
                'insp_notes' => 'Dimple depth is 0.060". 2.19" rings, +0.250"/-0.130". Ring ID to be ground flush. Use 5.985" to drift. Ends must be cleaned.',
                'layer_1_mesh' => '',
                'layer_1_width' => 0,
                'layer_2_mesh' => '',
                'layer_2_width' => 0,
                'drainage_1_mesh' => '',
                'drainage_1_width' => '0',
                'drainage_2_mesh' => '',
                'drainage_2_width' => 0,
                'blank_length_plus' => 0,
                'blank_length_minus' => 0,
                'depth_of_dimple' => 0,
                'is_louver' => 0,
                'depth_of_dimple_plus' => 0,
                'depth_of_dimple_minus' => 0,
                'blank_end' => 0,
                'blank_end_plus' => 0,
                'blank_end_minus' => 0,
                'cutoff_length_plus' => 0,
                'cutoff_length_minus' => 0,
                'drawing_number' => '',
                'table_height' => 0,
                'die_position' => 0,
                'shrouded_cutoff_length' => 0,
                'shrouded_cutoff_length_plus' => 0,
                'shrouded_cutoff_length_minus' => 0,
                'rouselle' => 0,
                'niagara' => 0,
                'seyi' => 0,
                'blank_area_input' => 0,
                'cycles_input' => 0,
                'linear_feet_input' => 0,
                'die_stamp' => '1/2 x 1 inline',
                'progression' => 0,
                'geo_job' => 0,
                'act_mill_angle' => 0,
                'table_position' => 0
            ],
            [
                'description' => 'PERF TUBE, 6.24"OD, 304L',
                'customer_id' => 3,
                'type' => '416L',
                'part' => '01847575',
                'gage' => 20,
                'holes' => 0.06,
                'centers' => 0.06,
                'pattern' => 'Inline',
                'dim' => 7.69,
                'dim_plus' => 0.03,
                'dim_minus' => 0.03,
                'is_od' => 1,
                'cutoff_length' => 202,
                'finished_length' => 200,
                'final_length_geo' => 0,
                'length_plus' => 0.125,
                'length_minus' => 0.125,
                'strip' => 7,
                'drift' => '7.460',
                'mill' => 1,
                'ring1_min_input' => 0,
                'ring1_max_input' => 0,
                'ring2_min_input' => 0,
                'ring2_max_input' => 0,
                'die' => 180,
                'filter_mesh' => '',
                'notes' => 'Dimple depth is 0.060". 2.19" rings, +0.250"/-0.130". Ring ID to be ground flush. Use 5.985" to drift. Ends must be cleaned.',
                'drawing' => '',
                'insp_notes' => 'Dimple depth is 0.060". 2.19" rings, +0.250"/-0.130". Ring ID to be ground flush. Use 5.985" to drift. Ends must be cleaned.',
                'layer_1_mesh' => '',
                'layer_1_width' => 0,
                'layer_2_mesh' => '',
                'layer_2_width' => 0,
                'drainage_1_mesh' => '',
                'drainage_1_width' => '0',
                'drainage_2_mesh' => '',
                'drainage_2_width' => 0,
                'blank_length_plus' => 0,
                'blank_length_minus' => 0,
                'depth_of_dimple' => 0,
                'is_louver' => 0,
                'depth_of_dimple_plus' => 0,
                'depth_of_dimple_minus' => 0,
                'blank_end' => 0,
                'blank_end_plus' => 0,
                'blank_end_minus' => 0,
                'cutoff_length_plus' => 0,
                'cutoff_length_minus' => 0,
                'drawing_number' => '',
                'table_height' => 0,
                'die_position' => 0,
                'shrouded_cutoff_length' => 0,
                'shrouded_cutoff_length_plus' => 0,
                'shrouded_cutoff_length_minus' => 0,
                'rouselle' => 0,
                'niagara' => 0,
                'seyi' => 0,
                'blank_area_input' => 0,
                'cycles_input' => 0,
                'linear_feet_input' => 0,
                'die_stamp' => '1/2 x 1 inline',
                'progression' => 0,
                'geo_job' => 0,
                'act_mill_angle' => 0,
                'table_position' => 0
            ]
        ];
        foreach ($itemArr as $item) {
            Part::create($item);
        }
    }
}
